# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
