# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170721_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='url',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='autor',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
