# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170824_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyznanie',
            old_name='url',
            new_name='code',
        ),
    ]
