# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170824_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyznanie',
            name='code',
        ),
    ]
