# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_wyznanie_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='code',
            field=models.CharField(default='aaaaaaaaaaaa', max_length=12),
            preserve_default=False,
        ),
    ]
