# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-25 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_wyznanie_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
