# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-25 18:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20170825_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(default=datetime.datetime.now)),
                ('data_edycji', models.DateTimeField(default=datetime.datetime.now)),
                ('is_hidden', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wyznanie',
            name='id',
        ),
        migrations.AddField(
            model_name='wyznanie',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='code',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='komentarz',
            name='id_wyznania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Wyznanie'),
        ),
    ]
