# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-26 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170825_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
