# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20170826_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
