# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170830_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
