# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_wyznanie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
