# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170830_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyznanie',
            name='slug',
            field=models.SlugField(),
        ),
    ]
