# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-03 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_wyznanie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyznanie',
            old_name='likes',
            new_name='favourites',
        ),
    ]
