# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-03 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170903_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='slug',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
