# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_wyznanie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
