# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_wyznanie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyznanie',
            name='slug',
        ),
    ]
