# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_komentarz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentarz',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
