# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170915_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
