# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-15 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_wyznanie_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyznanie',
            name='is_banned',
        ),
    ]
