# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-20 14:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0027_remove_wyznanie_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(default=datetime.datetime.now)),
                ('data_edycji', models.DateTimeField(default=datetime.datetime.now)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='answear',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answear',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comment_answear_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answear',
            name='id_komentarza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Komentarz'),
        ),
        migrations.AddField(
            model_name='answear',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_answear_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
