# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20170920_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='answear',
            name='code',
            field=models.CharField(default='aaaaaaaaaaaa', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
