# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-20 15:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_answear_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('tresc', models.TextField()),
                ('data_dodania', models.DateTimeField(default=datetime.datetime.now)),
                ('data_edycji', models.DateTimeField(default=datetime.datetime.now)),
                ('is_hidden', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_answer_dislikes', to=settings.AUTH_USER_MODEL)),
                ('id_komentarza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Komentarz')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_answer_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
