# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-20 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answear',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='id_komentarza',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Answear',
        ),
    ]
