# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170920_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
