# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_wyznanie_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyznanie',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wyznanie',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
